### ISSUE TITLE
Possibility for internal use without https?

### ISSUE THREAD

**Issue by DocBrown101** [knrdl/casa#2]
Hello, I would like to use casa internally and test something, but unfortunately I fail already at the login. My guess is that the login only works with an SSL secured connection.

I tried this URL because it wouldn't start without it:
AUTH_API_URL: http://192.168.0.220:8080

Unfortunately, this did not help.

Maybe there is another workaround so that I can log in here in my LAN?

**Comment by knrdl** [comment]
Hi, 
a workaround for tests is described here: https://github.com/knrdl/casa#2-authentication (no https required)
TL;DR: 
AUTH_API_URL: https://example.org/
Then login with any credentials

**Comment by DocBrown101** [comment]
Ok thanks! I thought maybe there is a local solution that works with a password.
